name = "data-worker-dashboard"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Bindings to KV Namespace
[[kv_namespaces]]
binding = "DATA_KV"
id = "6efdd5545c9b43ef9160d55c271d8829"

[vars]
# Optional GitHub Trigger Configurations
GITHUB_OWNER = ""
GITHUB_REPO = ""
# GITHUB_PAT should be set via secret: `wrangler secret put GITHUB_PAT`

